package com.raven.form;

import com.raven.dialog.Message;
import com.raven.main.Main;
import java.awt.Image;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import qlsmp.DAO.CTPNDao;
import qlsmp.DAO.NCCDao;
import qlsmp.DAO.NhanVienDAO;
import qlsmp.DAO.PhieuNhapDAO;
import qlsmp.DAO.SanPhamDAO;
import qlsmp.Model.CTPN;
import qlsmp.Model.NCC;
import qlsmp.Model.NhanVien;
import qlsmp.Model.PhieuNhap;
import qlsmp.Model.SanPham;
import qlsmp.utis.Auth;
import qlsmp.utis.XImage;

/**
 *
 * @author My Laptop
 */
public class Form_HoaDonNhapHang extends javax.swing.JPanel {

    SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form HD
     */
    public Form_HoaDonNhapHang() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lblTongTienPN2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblChieuKhau3 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lblTongThanhTienPN2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnLoc = new javax.swing.JButton();
        dateTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dateDenNgay = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblMaPN = new javax.swing.JLabel();
        lblMaNCC = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTenNCC = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblUserNV = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblChietKhau = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        lblTongThanhTien = new javax.swing.JLabel();
        btnLoc1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCTPN = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSLSP = new javax.swing.JLabel();
        lblSoMatHang = new javax.swing.JLabel();
        lblTongTienPN = new javax.swing.JLabel();
        lblTongThanhTienPN = new javax.swing.JLabel();
        lblChieuKhau2 = new javax.swing.JLabel();
        lblGiaNhapSP = new javax.swing.JLabel();
        lblThanhTienSP = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        hinh = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(168, 201, 237));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 0, new java.awt.Color(204, 204, 204)));

        lblTongTienPN2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongTienPN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongTienPN2.setText("200.000,00");

        jLabel26.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(11, 52, 106));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Tổng tiền:");

        jLabel27.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(11, 52, 106));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Chiếc khấu:");

        lblChieuKhau3.setBackground(new java.awt.Color(255, 255, 255));
        lblChieuKhau3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChieuKhau3.setText("0");
        lblChieuKhau3.setOpaque(true);

        jLabel48.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(11, 52, 106));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel48.setText("Còn");

        lblTongThanhTienPN2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongThanhTienPN2.setForeground(new java.awt.Color(255, 0, 0));
        lblTongThanhTienPN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongThanhTienPN2.setText("200.000,00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblTongTienPN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblChieuKhau3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblTongThanhTienPN2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTienPN2)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChieuKhau3)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongThanhTienPN2)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(168, 201, 237));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(204, 204, 204)));

        btnLoc.setBackground(new java.awt.Color(0, 0, 102));
        btnLoc.setForeground(new java.awt.Color(255, 255, 255));
        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        dateTuNgay.setBackground(new java.awt.Color(255, 255, 255));
        dateTuNgay.setDateFormatString("dd-MM-yyyy");

        jLabel24.setBackground(new java.awt.Color(11, 52, 106));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(11, 52, 106));
        jLabel24.setText("Từ ngày");

        jLabel25.setBackground(new java.awt.Color(11, 52, 106));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(11, 52, 106));
        jLabel25.setText("Đến ngày");

        dateDenNgay.setBackground(new java.awt.Color(255, 255, 255));
        dateDenNgay.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLoc)
                    .addComponent(jLabel25)
                    .addComponent(dateDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(dateTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(168, 201, 237));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(11, 52, 106));
        jLabel5.setText("Mã hóa đơn:");

        lblMaPN.setBackground(new java.awt.Color(255, 255, 255));
        lblMaPN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaPN.setText("123");
        lblMaPN.setOpaque(true);

        lblMaNCC.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaNCC.setText("123");
        lblMaNCC.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(11, 52, 106));
        jLabel8.setText("Mã nhà cung cấp:");

        lblTenNCC.setBackground(new java.awt.Color(255, 255, 255));
        lblTenNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenNCC.setText("Nhà cung cấp 1");
        lblTenNCC.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(11, 52, 106));
        jLabel10.setText("Ngày tạo:");

        lblNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayTao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgayTao.setText("2000-12-12");
        lblNgayTao.setOpaque(true);

        jLabel12.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(11, 52, 106));
        jLabel12.setText("Tên nhà cung cấp:");

        lblUserNV.setBackground(new java.awt.Color(255, 255, 255));
        lblUserNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserNV.setText("Tâm Nguyễn");
        lblUserNV.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(11, 52, 106));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Username Nhân viên:");

        jLabel15.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(11, 52, 106));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Chiếu khấu:");

        lblChietKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblChietKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChietKhau.setText("123");
        lblChietKhau.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaPN, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addGap(153, 153, 153)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserNV, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(lblChietKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblUserNV))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChietKhau)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(lblNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTenNCC)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(lblMaPN))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMaNCC)
                                .addComponent(jLabel8)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(168, 201, 237));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 2, 0, new java.awt.Color(204, 204, 204)));

        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Mã nhà cung cấp", "Mã nhân viên", "Ngày tạo", "Tổng tiền", "Chiếc khấu", "Thành tiền"
            }
        ));
        tblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhieuNhap);

        lblTongThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongThanhTien.setForeground(new java.awt.Color(255, 0, 0));
        lblTongThanhTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongThanhTien.setText("1.200.000.00");

        btnLoc1.setBackground(new java.awt.Color(0, 0, 102));
        btnLoc1.setForeground(new java.awt.Color(255, 255, 255));
        btnLoc1.setText("Xóa");
        btnLoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoc1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnLoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(763, 763, 763)
                        .addComponent(lblTongThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongThanhTien)
                    .addComponent(btnLoc1))
                .addGap(7, 7, 7))
        );

        jPanel3.setBackground(new java.awt.Color(168, 201, 237));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(204, 204, 204)));

        tblCTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Màu sắc", "Số lượng", "Giá nhập", "Thành tiền"
            }
        ));
        tblCTPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTPNMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCTPN);

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(11, 52, 106));
        jLabel1.setText("Số mặt hàng:");

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(11, 52, 106));
        jLabel2.setText("Số lượng:");

        lblSLSP.setBackground(new java.awt.Color(255, 255, 255));
        lblSLSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSLSP.setText("2");
        lblSLSP.setOpaque(true);

        lblSoMatHang.setBackground(new java.awt.Color(255, 255, 255));
        lblSoMatHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoMatHang.setText("4");
        lblSoMatHang.setOpaque(true);

        lblTongTienPN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongTienPN.setForeground(new java.awt.Color(255, 51, 51));
        lblTongTienPN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongTienPN.setText("1.200.000.00");

        lblTongThanhTienPN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongThanhTienPN.setForeground(new java.awt.Color(255, 51, 51));
        lblTongThanhTienPN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongThanhTienPN.setText("1.200.000.00");

        lblChieuKhau2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblChieuKhau2.setForeground(new java.awt.Color(255, 51, 51));
        lblChieuKhau2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChieuKhau2.setText("0");

        lblGiaNhapSP.setBackground(new java.awt.Color(255, 255, 255));
        lblGiaNhapSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGiaNhapSP.setText("200.000,00");
        lblGiaNhapSP.setOpaque(true);

        lblThanhTienSP.setBackground(new java.awt.Color(255, 255, 255));
        lblThanhTienSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThanhTienSP.setText("200.000,00");
        lblThanhTienSP.setOpaque(true);

        jLabel22.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(11, 52, 106));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Giá nhập:");

        jLabel23.setFont(new java.awt.Font("Roboto Condensed Light", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(11, 52, 106));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Thành tiền:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSoMatHang, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(lblSLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(358, 358, 358)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTongTienPN, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(lblGiaNhapSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChieuKhau2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblThanhTienSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTongThanhTienPN, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoMatHang)
                            .addComponent(lblTongTienPN)
                            .addComponent(lblTongThanhTienPN)
                            .addComponent(lblChieuKhau2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSLSP)
                            .addComponent(lblGiaNhapSP)
                            .addComponent(lblThanhTienSP)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(168, 201, 237));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 0, new java.awt.Color(204, 204, 204)));

        hinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        if (dateTuNgay.getDate() == null || dateDenNgay.getDate() == null) {
            this.showMessage("Vui lòng nhập đủ thông tin");
        } else {
            if (dateTuNgay.getDate().compareTo(dateDenNgay.getDate()) > 0) {
                this.showMessage("Từ ngày phải lớn hơn đến ngày");
            } else {
                index = true;
                listPN = PNdao.selectBetweenAnd(date.format(dateTuNgay.getDate()), date.format(dateDenNgay.getDate()));
                this.fillTablePN(listPN);
                this.TongPN();
            }
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void tblPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapMouseClicked
        int row = tblPhieuNhap.getSelectedRow();
        maPN = (int) modelPN.getValueAt(row, 0);
        PhieuNhap enity = PNdao.selecteByID(maPN);
        this.setFormPN(enity);
        this.fillTableCTPN(maPN);
        CTPN ctpn = new CTPN();
        this.setFormCTPN(ctpn);
        lblSoMatHang.setText(tblCTPN.getRowCount() + "");
    }//GEN-LAST:event_tblPhieuNhapMouseClicked

    private void tblCTPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTPNMouseClicked
        int row = tblCTPN.getSelectedRow();
        maCTPN = (int) modelCTPN.getValueAt(row, 0);
        CTPN enity = CTPNdao.selecteByID(maCTPN);
        this.setFormCTPN(enity);
    }//GEN-LAST:event_tblCTPNMouseClicked

    private void btnLoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoc1ActionPerformed
        Delete();
    }//GEN-LAST:event_btnLoc1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnLoc1;
    private com.toedter.calendar.JDateChooser dateDenNgay;
    private com.toedter.calendar.JDateChooser dateTuNgay;
    private javax.swing.JLabel hinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblChietKhau;
    private javax.swing.JLabel lblChieuKhau2;
    private javax.swing.JLabel lblChieuKhau3;
    private javax.swing.JLabel lblGiaNhapSP;
    private javax.swing.JLabel lblMaNCC;
    private javax.swing.JLabel lblMaPN;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblSLSP;
    private javax.swing.JLabel lblSoMatHang;
    private javax.swing.JLabel lblTenNCC;
    private javax.swing.JLabel lblThanhTienSP;
    private javax.swing.JLabel lblTongThanhTien;
    private javax.swing.JLabel lblTongThanhTienPN;
    private javax.swing.JLabel lblTongThanhTienPN2;
    private javax.swing.JLabel lblTongTienPN;
    private javax.swing.JLabel lblTongTienPN2;
    private javax.swing.JLabel lblUserNV;
    private javax.swing.JTable tblCTPN;
    private javax.swing.JTable tblPhieuNhap;
    // End of variables declaration//GEN-END:variables

    List<PhieuNhap> listPN = new ArrayList<>();
    List<CTPN> listCTPN = new ArrayList<>();
    PhieuNhapDAO PNdao = new PhieuNhapDAO();
    CTPNDao CTPNdao = new CTPNDao();

    String columsPN[] = {"Mã phiếu nhập", "Ngày tạo", "Tên nhà cung cấp", "Tên nhân viên", "Tổng tiền", "Chiết khẩu", "Thành tiền"};
    DefaultTableModel modelPN = new DefaultTableModel(columsPN, 0);

    String columsCTPN[] = {"Mã CTPN", "Mã sản phẩm", "Tên sản phẩm", "Màu sắc", "Số lượng", "Giá nhập", "Thành tiền"};
    DefaultTableModel modelCTPN = new DefaultTableModel(columsCTPN, 0);

    int maPN, maCTPN;
    boolean index = false;

    void init() {
        tblPhieuNhap.setDefaultEditor(Object.class, null);
        tblCTPN.setDefaultEditor(Object.class, null);
        index = false;
        clearPage();
        listPN = PNdao.selectAllMonth();
        fillTablePN(listPN);
        this.TongPN();
    }

    private void showMessage(String message) {
        Message obj = new Message(Main.getFrames()[0], true);
        obj.showMessage(message);
    }

    void clearPage() {
        PhieuNhap pn = new PhieuNhap();
        CTPN ctpn = new CTPN();
        setFormPN(pn);
        setFormCTPN(ctpn);
        modelCTPN.setRowCount(0);
        modelPN.setRowCount(0);
        tblCTPN.setModel(modelCTPN);
        tblPhieuNhap.setModel(modelPN);
        dateTuNgay.setCalendar(null);
        dateDenNgay.setCalendar(null);
        lblSoMatHang.setText(null);
    }

    void setFormPN(PhieuNhap enity) {
//        SimpleDateFormat date2 = new SimpleDateFormat("dd-MM-yyyy");
        DecimalFormat decimalFormat = new DecimalFormat("#,###,##0.0");
        lblMaPN.setText(enity.getMaPN() + "");
        lblMaNCC.setText(enity.getMaNCC() + "");
        lblNgayTao.setText(enity.getNgayTao());
        NCCDao nccdao = new NCCDao();
        NCC ncc = nccdao.selecteByID(enity.getMaNCC());
        if (ncc == null) {
            lblTenNCC.setText(null);
        } else {
            lblTenNCC.setText(ncc.getTenNCC());
        }
        NhanVienDAO nvdao = new NhanVienDAO();
        NhanVien nv = nvdao.selectById(enity.getMaNV());
        if (nv == null) {
            lblUserNV.setText(null);
        } else {
            lblUserNV.setText(nv.getUsername());
        }
        lblChietKhau.setText(enity.getChietKhau() + "%");

        lblTongTienPN.setText(decimalFormat.format(enity.getTongTien()));
        lblChieuKhau2.setText(enity.getChietKhau() + "%");
        lblTongThanhTienPN.setText(decimalFormat.format(enity.getThanhTien()));

        lblTongTienPN2.setText(decimalFormat.format(enity.getTongTien()));
        lblChieuKhau3.setText(enity.getChietKhau() + "%");
        lblTongThanhTienPN2.setText(decimalFormat.format(enity.getThanhTien()));
    }

    void setFormCTPN(CTPN enity) {
        DecimalFormat decimalFormat = new DecimalFormat("#,###,##0.0");
        lblSLSP.setText(enity.getSl() + "");
        lblGiaNhapSP.setText(decimalFormat.format(enity.getGiaNhap()));
        lblThanhTienSP.setText(decimalFormat.format(enity.getThanhTien()));
        SanPhamDAO spdao = new SanPhamDAO();
        SanPham sp = spdao.selecteByID(enity.getMaSP());
        if (sp == null) {
            hinh.setIcon(null);
        } else {
            if (sp.getHinh() != null) {
                setHinhAnh(sp.getHinh(), hinh);
            } else {
                hinh.setIcon(null);
            }
        }
    }

    void fillTablePN(List<PhieuNhap> listPN) {
        DecimalFormat decimalFormat = new DecimalFormat("#,###,##0.0");
        modelPN.setRowCount(0);
        for (PhieuNhap enity : listPN) {
            String thanhTien = decimalFormat.format(enity.getThanhTien());
            String tongTien = decimalFormat.format(enity.getTongTien());
            NCCDao nccdao = new NCCDao();
            NhanVienDAO nvdao = new NhanVienDAO();
            NCC ncc = nccdao.selecteByID(enity.getMaNCC());
            NhanVien nv = nvdao.selectById(enity.getMaNV());
            String chietkhau = enity.getChietKhau() + "%";
            modelPN.addRow(new Object[]{enity.getMaPN(), enity.getNgayTao(), ncc.getTenNCC(), nv.getHoTen(), tongTien, chietkhau, thanhTien});
        }
        tblPhieuNhap.setModel(modelPN);
    }

    void fillTableCTPN(int id) {
        DecimalFormat decimalFormat = new DecimalFormat("#,###,##0.0");
        modelCTPN.setRowCount(0);
        listCTPN = CTPNdao.selecteByMaPN(id);
        for (CTPN enity : listCTPN) {
            SanPhamDAO spdao = new SanPhamDAO();
            SanPham sp = spdao.selecteByID(enity.getMaSP());
            String thanhTien = decimalFormat.format(enity.getThanhTien());
            modelCTPN.addRow(new Object[]{enity.getMaCTPN(), enity.getMaSP(), sp.getTenSP(), enity.getTenMau(), enity.getSl(), enity.getGiaNhap(), thanhTien});
        }
        tblCTPN.setModel(modelCTPN);
    }

    void TongPN() {
        DecimalFormat decimalFormat = new DecimalFormat("#,###,##0.0");
        float tongTien = 0;
        int row = tblPhieuNhap.getRowCount();
        System.out.println("row" + row);
        for (int i = 0; i < row; i++) {
            try {
                Number number = decimalFormat.parse((String) tblPhieuNhap.getValueAt(i, 6));
                System.out.println("tiền 2:" + number);
                float tien2 = number.floatValue();

                tongTien += tien2;
            } catch (Exception e) {
            }
        }
        lblTongThanhTien.setText(decimalFormat.format(tongTien));
    }

    public void setHinhAnh(String path, JLabel hinh) {
        if (path != null) {
            ImageIcon icon = XImage.read(path);
            Image image = icon.getImage();
            Image image2 = image.getScaledInstance(230, 210, Image.SCALE_SMOOTH);
            hinh.setToolTipText(path);
            hinh.setIcon(new ImageIcon(image2));
        } else {
            hinh.setIcon(null);
        }
    }

    void Delete() {
        if (Auth.user.isChucVu()) {
            //PhieuNhap pn = PNdao.selecteByID(maPN);
            CTPNdao.deleteByMaPN(maPN);
            PNdao.delete(maPN);
            if (index == false) {
                listPN = PNdao.selectAllMonth();

            } else {
                listPN = PNdao.selectBetweenAnd(date.format(dateTuNgay.getDate()), date.format(dateDenNgay.getDate()));
            }
            fillTablePN(listPN);
            modelCTPN.setRowCount(0);
            this.showMessage("Xóa thành công!");
        } else {
            this.showMessage("Bạn không có quyền xóa hóa đơn!");
        }
    }
}
